### ISSUE TITLE
error when running `main.py`

### ISSUE THREAD

**Issue by rrpelgrim** [Boburmirzo/chatgpt-api-python-sales#7]
Thanks for creating this awesome repo :D 
I've just tried to run `main.py` (locally after cloning the repo, on macOS) and am encountering  the following error (truncated):

```
...
 File "/Users/rpelgrim/mambaforge/envs/gpt-app/lib/python3.11/site-packages/pathway/internals/graph_runner/operator_handler.py", line 129, in _run
    materialized_table = self.scope.connector_table(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No such file or directory (os error 2)
Occurred here:
    Line: sales_data = pw.io.jsonlines.read(
    File: /Users/rpelgrim/Documents/git/my-forks/chatgpt-api-python-sales/examples/api/app.py:17
```

When I look at `app.py` it seems to be looking for a `jsonlines` file in `./examples/data` but that directory does not exist. I see `examples/csv` and `examples/rainforest`. Happy to help contribute except I'm not sure which of these directories to point to. Any help appreciated :)

Relevant lines from `app.py`:
```python
 # Real-time data coming from external data sources such as jsonlines file
    sales_data = pw.io.jsonlines.read(
        "./examples/data",
        schema=DataInputSchema,
        mode="streaming"
    )
```

**Comment by rrpelgrim** [comment]
JFYI - I'm getting the same error when running the Killercoda version:
https://killercoda.com/pathway/scenario/chatgpt-api-python-sales

**Comment by Boburmirzo** [comment]
@rrpelgrim Thank you for reporting this issue!

Yes, it seems the data folder was removed accidentally when I upgraded the LLM App version on this commit.

https://github.com/Boburmirzo/chatgpt-api-python-sales/commit/3a08cbf148db2d2d704cc57f55eda6ea95d72286

Now it should work. Adding a data folder fixed the issue. Probably, killercoda version also runs from this repo main branch.
